# Указываем базовый образ
FROM ubuntu:20.04

# Устанавливаем и обновляем зависимости
RUN apt-get update && apt-get install -y \
    build-essential \
    curl

# ONBUILD - execution is defered until the child image build begins
ONBUILD ADD . /src

USER nobody

