Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_architecture = "arm64"
  config.vm.box_version = "202401.31.0"

  config.vm.provider "vmware_desktop" do |v|
    v.cpus = 4
    v.memory = 4096
    v.gui = false
    v.linked_clone = true
  end

  # Configure the VM to use bridged networking
  config.vm.network "public_network"
end
